name: Docker

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write

    concurrency:
      group: ${{ github.workflow_ref }}-build-${{ matrix.version }}-${{ matrix.context }}
      cancel-in-progress: false

    strategy:
      fail-fast: false
      matrix:
        version:
        - "6.1.1"
        context:
        - "nvidia-ubuntu22.04"
        - "slim"
        include:
        - version: "6.1.1"
          ref: "6.1"
        # NOTE: `cuda` should represent the highest version the nvidia SDK supports
        # REF: https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html
        - context: nvidia-ubuntu22.04
          nvidia_video_codec_sdk: "12.1.14.0"
          nvidia_video_codec_sdk_short: "12.1"
          cuda: "12.1.1"
        - context: nvidia-ubuntu22.04
          nvidia_video_codec_sdk: "12.0.16.1"
          nvidia_video_codec_sdk_short: "12.0"
          cuda: "11.8.0"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      id: config
      uses: actions/github-script@v7
      env:
        GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
      with:
        script: |
          const os = require('os')

          core.setOutput('nproc', os.cpus().length * 2)

          core.setOutput('image-owner', process.env.GITHUB_REPOSITORY_OWNER)
          core.setOutput('image-name', process.env.GITHUB_REPOSITORY_NAME.replace(/^docker-/, ''))

    - name: Setup - buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup - Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup - Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Setup - Docker image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ steps.config.outputs.image-owner }}/${{ steps.config.outputs.image-name }}
          ghcr.io/${{ steps.config.outputs.image-owner }}/${{ steps.config.outputs.image-name }}
        flavor: |
          latest=false
          suffix=-nvidiasdk${{ matrix.nvidia_video_codec_sdk_short }}
        tags: |
          type=semver,pattern={{major}}.{{minor}},value=${{ matrix.version }}
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ matrix.version }}

    - name: Build
      uses: docker/build-push-action@v5
      id: build
      with:
        context: ${{ matrix.context }}
        build-args: |
          version=${{ matrix.ref || matrix.version }}
          cuda=${{ matrix.cuda }}
          nvidia_video_codec_sdk=${{ matrix.nvidia_video_codec_sdk }}
          repo=${{ matrix.repo || 'FFmpeg/FFmpeg' }}
          makeflags=-j${{ steps.config.outputs.nproc }}
        push: true
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
