name: Docker

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        version:
        - "6.0.0"
        - "5.1.2"
        - "5.0.2"
        flavor:
        - base
        - slim
        - cuda-12.0
        - cuda-11.0
        - cuda-10.0
        include:
        - version: "6.0.0"
          gitTag: "6.0"
        - flavor: cuda-12.1
          context: nvidia-ubuntu20.04
          cuda: 12.1.0
          nv_codecs: 12.0.16.0
        - flavor: cuda-11.0
          context: nvidia-ubuntu20.04
          cuda: 11.0.3
          nv_codecs: 10.0.26.2

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure
      id: config
      run: |-
        NPROC=$(nproc)

        echo "NPROC=$((NPROC*2+1))" >> $GITHUB_ENV
        echo "NPROC=$((NPROC*2+1))" >> $GITHUB_OUTPUT

        echo "repo-owner=${{ github.repository_owner }}" >> $GITHUB_OUTPUT
        echo "repo-name=${GITHUB_REPOSITORY#*/docker-}" >> $GITHUB_OUTPUT

    - name: Setup - buildx
      uses: docker/setup-buildx-action@v2

    - name: Setup - Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup - Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Setup - Docker image metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ steps.config.outputs.repo-owner }}/${{ steps.config.outputs.repo-name }}
          ghcr.io/${{ steps.config.outputs.repo-owner }}/${{ steps.config.outputs.repo-name }}
        flavor: |
          latest=${{ !!matrix.latest }}
        tags: |
          type=semver,pattern={{major}}.{{minor}},value=${{ matrix.version }},enable=${{ !matrix.flavor }}
          type=semver,pattern={{major}}.{{minor}},suffix=-${{ matrix.flavor }},value=${{ matrix.version }},enable=${{ !!matrix.flavor }}

    - name: Build
      uses: docker/build-push-action@v4
      id: build
      with:
        context: ${{ matrix.context || matrix.flavor }}
        build-args: |
          version=${{ matrix.gitTag || matrix.version }}
          cuda=${{ matrix.cuda }}
          nv_codecs=${{ matrix.nv_codecs }}
          MAKEFLAGS=-j${{ env.NPROC }}
        push: true
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
