name: Docker

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        version: ["4.4.1"]
        flavor: ["slim"]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup - buildx
      uses: docker/setup-buildx-action@v2

    - name: Setup - Docker Hub
      uses: docker/login-action@v2
      if: ${{ !steps.config.outputs.skip-push-to-registry }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup - Github Container Registry
      uses: docker/login-action@v2
      if: ${{ !steps.config.outputs.skip-push-to-registry }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Setup - Docker image metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/ffmpeg
        flavor: |
          suffix=-${{ matrix.flavor }}
        tags: |
          type=semver,pattern={{major}}.{{minor}},value=${{ matrix.version }}

    - name: Build
      uses: docker/build-push-action@v3
      id: build
      with:
        context: ${{ matrix.flavor }}
        build-args: |
          version=${{ matrix.version }}
          MAKEFLAGS=-j8
        push: ${{ !steps.config.outputs.skip-push-to-registry }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
